name: "yamllint"
description: "installs yaml lint"
inputs:
  path:
    description: "Path to run linter on"
    required: true
  config:
    description: "Optional config-path to override the config if needed"
    required: false
    default: "yamllint/config.yaml"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: distributed-technologies/gha-yamllint
        path: yamllint

    - name: Install yamllint
      run: pip install yamllint
      shell: bash

    - name: Lint YAML files
      run: "yamllint -s -d ${{ inputs.config }} ${{ inputs.path }}"
      shell: bash
