# Rules: https://yamllint.readthedocs.io/en/stable/rules.html
---
extends: default

rules:
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
  line-length: disable
  truthy:
    check-keys: false
